name: google_flow
description: "A simple English-Spanish translation chat app."
publish_to: 'none' # This prevents accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.29.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1
  logger: ^2.0.0
  web_socket_channel: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.2  # Add js package for JavaScript interop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and update the following if we have assets we wanna include
  assets:
    - web/pcm-processor.js


  # Uncomment and update the following if you use custom fonts later on to make it look purrty 
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700