name: google_flow
description: "A new Flutter project for Google Flow integration."
publish_to: 'none' # This prevents accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  http: ^1.3.0
  image_picker: ^1.1.2
  flutter_webrtc: ^0.12.12
  socket_io_client: ^3.0.2
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  path_provider: ^2.1.5
  record: ^5.2.1
  just_audio: ^0.9.46

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Uncomment and update the following if we have assets we wanna  include
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Uncomment and update the following if you use custom fonts later on to make it look purrty 
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700